#!/usr/bin/env python3
"""Plan deterministic first-review batches over the ranked Fortnite semantic queue."""
from __future__ import annotations

import argparse
import hashlib
import gzip
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

from tools.knowledge.build_fortnite_semantic_review_work_batch import build, iter_jsonl

VERSION = "fortnite-semantic-review-batch-plan/v1"
DEFAULT_QUEUE = (
    ROOT
    / "knowledge"
    / "libraries"
    / "lego-minifigure-customs"
    / "data"
    / "semantic-review-batches"
    / "fortnite-first-review-queue-v1.jsonl.gz"
)
DEFAULT_BATCH_DIR = (
    ROOT
    / "knowledge"
    / "libraries"
    / "lego-minifigure-customs"
    / "data"
    / "semantic-review-batches"
)
DEFAULT_OUTPUT = DEFAULT_BATCH_DIR / "fortnite-first-review-batch-plan.json"


def sha256_file(path: Path) -> str:
    digest = hashlib.sha256()
    opener = gzip.open if path.suffix == ".gz" else open
    with opener(path, "rb") as handle:
        for chunk in iter(lambda: handle.read(1024 * 1024), b""):
            digest.update(chunk)
    return digest.hexdigest()


def build_plan(
    queue_path: Path = DEFAULT_QUEUE,
    batch_dir: Path = DEFAULT_BATCH_DIR,
    *,
    batch_size: int = 25,
    min_priority_score: float = 6.0,
) -> dict:
    if batch_size <= 0:
        raise ValueError("batch_size must be positive")

    rows = list(iter_jsonl([queue_path]))
    eligible = []
    for row in rows:
        try:
            score = float(row.get("review_priority_score") or 0.0)
        except (TypeError, ValueError):
            score = 0.0
        if score >= min_priority_score:
            eligible.append(row)

    eligible.sort(
        key=lambda row: (
            -float(row.get("review_priority_score") or 0.0),
            str(row.get("translation_pair_id") or ""),
        )
    )

    batches = []
    for offset in range(0, len(eligible), batch_size):
        batch_index = offset // batch_size + 1
        result = build(
            rows,
            mode="first_review",
            limit=batch_size,
            offset=offset,
            min_priority_score=min_priority_score,
            reviewer_id="unassigned",
            reviewer_type="human",
        )
        selected = result["items"]
        if not selected:
            continue
        filename = f"fortnite-first-review-batch-{batch_index:04d}.json"
        path = batch_dir / filename
        batches.append(
            {
                "batch_index": batch_index,
                "batch_id": result["batch_id"],
                "offset": offset,
                "limit": batch_size,
                "selected_records": len(selected),
                "top_priority_score": selected[0]["review_priority_score"],
                "bottom_priority_score": selected[-1]["review_priority_score"],
                "first_translation_pair_id": selected[0]["translation_pair_id"],
                "last_translation_pair_id": selected[-1]["translation_pair_id"],
                "path": path.relative_to(ROOT).as_posix(),
                "materialized": path.exists(),
                "status": "materialized" if path.exists() else "planned",
            }
        )

    return {
        "schema": "fortnite-semantic-review-batch-plan/v1",
        "processor_version": VERSION,
        "queue_path": queue_path.relative_to(ROOT).as_posix(),
        "queue_sha256": sha256_file(queue_path),
        "queue_hash_scope": "decompressed_jsonl_bytes",
        "mode": "first_review",
        "min_priority_score": min_priority_score,
        "batch_size": batch_size,
        "eligible_records": len(eligible),
        "batch_count": len(batches),
        "materialized_batch_count": sum(row["materialized"] for row in batches),
        "planned_batch_count": sum(not row["materialized"] for row in batches),
        "batches": batches,
        "policy": [
            "Batch ordering is score-descending then translation_pair_id ascending.",
            "A pair belongs to exactly one first-review batch at this queue snapshot.",
            "Batch IDs are generated by the canonical work-batch builder.",
            "Materialization status reflects checked-in batch JSON files only.",
        ],
    }


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--queue", type=Path, default=DEFAULT_QUEUE)
    parser.add_argument("--batch-dir", type=Path, default=DEFAULT_BATCH_DIR)
    parser.add_argument("--output", type=Path, default=DEFAULT_OUTPUT)
    parser.add_argument("--batch-size", type=int, default=25)
    parser.add_argument("--min-priority-score", type=float, default=6.0)
    args = parser.parse_args()

    result = build_plan(
        args.queue,
        args.batch_dir,
        batch_size=args.batch_size,
        min_priority_score=args.min_priority_score,
    )
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(
        json.dumps(result, indent=2, ensure_ascii=False) + "\n",
        encoding="utf-8",
    )
    print(
        json.dumps(
            {
                key: value
                for key, value in result.items()
                if key != "batches"
            },
            indent=2,
        )
    )


if __name__ == "__main__":
    main()
